export const agreements = {
    "en": {
      "content-release": {
        "title": "Content Release Agreement",
        "p1": "This Content Release Agreement (“Agreement”) is made on the date signed below.",
        "p2": "<strong>1. Grant of Rights:</strong> The undersigned (“Releasor”) hereby irrevocably grants to the other undersigned party (“Releasee”) the right and permission to use, reproduce, publish, distribute, broadcast, exhibit, and otherwise exploit all photographs, videos, audio recordings, written text, likeness, image, or other media content (collectively, the “Content”) in which the Releasor appears or is identifiable, in any and all media now known or hereafter devised, including but not limited to print, television, radio, film, digital media, social media, advertising, promotional materials, and merchandise.",
        "p3": "<strong>2. Scope of Use:</strong> The rights granted herein are worldwide, perpetual, royalty-free, and may be assigned, transferred, or sublicensed by the Releasee at its sole discretion. The Releasee may edit, alter, combine, or otherwise modify the Content without restriction and without any obligation to notify or seek further approval from the Releasor.",
        "p4": "<strong>3. Compensation:</strong> The Releasor acknowledges that this release is given voluntarily and that any compensation (if any) is full and final consideration for the rights granted herein. No further payments or royalties shall be due in connection with any use of the Content.",
        "p5": "<strong>4. Waiver of Claims:</strong> The Releasor waives any right to inspect or approve the finished product, its use, or any accompanying text or copy. The Releasor releases and forever discharges the Releasee from any and all claims, demands, or causes of action that the Releasor may now or hereafter have, including but not limited to claims for defamation, invasion of privacy, violation of moral rights, or infringement of rights of publicity or personality arising out of or in connection with the use of the Content.",
        "p6": "<strong>5. Capacity:</strong> The Releasor affirms they are at least 18 years of age and have the full legal capacity to enter into this Agreement. If under 18, the signature of a parent or legal guardian is required.",
        "p7": "<strong>6. Entire Agreement:</strong> This document constitutes the entire agreement between the parties concerning the Content and supersedes any prior understandings or agreements, whether written or oral, regarding the subject matter herein. Any modifications or amendments will be void unless made in writing and signed by both parties.",
        "p8": "<strong>7. Governing Law:</strong> This Agreement shall be governed by and construed in accordance with the laws of the jurisdiction in which it is executed, without regard to its conflict of law principles."
      },
      "general-consent": {
        "title": "Sexual Consent Agreement",
        "p1": "This Sexual Consent Agreement (“Agreement”) is made on the date signed below. The undersigned individuals (collectively, the “Parties”) willingly and intentionally agree to the following terms:",
        "p2": "<strong>1. Voluntary Participation:</strong> Both Parties affirm that their participation in any sexual activity or contact is entirely voluntary, free from the use of force, coercion, duress, threats, blackmail, or any undue influence. Neither Party has been intimidated, bribed, or promised any reward or benefit in exchange for participation.",
        "p3": "<strong>2. Capacity and State of Mind:</strong> Both Parties confirm that, at the time of signing and during all agreed-upon activities: They are of the legal age of consent under the laws of the jurisdiction where this Agreement is made. They are of sound mind and full mental capacity to understand and agree to these terms. They are not under the influence of alcohol, drugs, medications, or any substance that impairs their judgment, understanding, or decision-making abilities. They have had adequate time to consider the implications of engaging in sexual activity and have asked any questions before signing.",
        "p4": "<strong>3. Understanding of Consent:</strong> The Parties acknowledge that: Consent must be informed, freely given, mutual, and ongoing. Consent can be withdrawn by either Party at any time, for any reason, without explanation. The withdrawal of consent requires the other Party to immediately cease all activity, without delay or argument. Past sexual activity with the other Party or with others does not imply or guarantee consent for future activity.",
        "p5": "<strong>4. Boundaries and Respect:</strong> The Parties agree to communicate clearly about their comfort levels, physical boundaries, emotional boundaries, and any other personal limitations before and during the activity. Both Parties commit to: Respect verbal and non-verbal cues indicating discomfort, hesitation, or the withdrawal of consent. Refrain from any act that is known or reasonably suspected to cause undue distress, harm, or emotional damage. Respect the personal dignity, privacy, and physical safety of the other Party at all times.",
        "p6": "<strong>5. Health and Safety:</strong> The Parties affirm that: They have disclosed any relevant health conditions, including sexually transmitted infections (STIs) or other diseases, that could reasonably affect the other Party’s decision to participate. They have discussed and mutually agreed upon any protective measures to be used during the activity, including contraception and hygiene standards. They will immediately inform the other Party if at any point they feel unwell, experience pain, distress, or any medical concern during the encounter.",
        "p7": "<strong>6. No Exploitation or Public Disclosure:</strong> The Parties agree that: No recording (audio, video, or photographic) of any sexual activity will take place without explicit, mutual consent at the time of recording. If any recordings are made, their use, storage, and sharing must be agreed upon in writing. No content, information, or personal details about the other Party will be shared publicly, online, or with third parties without express consent.",
        "p8": "<strong>7. Duration of Consent:</strong> This Agreement covers only the sexual activity taking place in the immediate time frame following its execution. It does not grant open-ended or permanent consent for future encounters. Any subsequent activity requires a new verbal or written agreement of consent.",
        "p9": "<strong>8. Mutual Release:</strong> Provided all activities remain within agreed-upon boundaries and any withdrawal of consent is immediately respected, each Party releases the other from liability for any claims, complaints, or disputes arising from the consensual nature of the encounter.",
        "p10": "<strong>9. Legal Limitations:</strong> Both Parties understand that: This Agreement does not waive or override any applicable laws regarding sexual assault, statutory rape, or the inability to provide legal consent. If either Party is later found to have lacked legal or mental capacity at the time of the encounter, this Agreement is null and void. A breach of any term of this Agreement, including failure to respect the withdrawal of consent, invalidates its protections for the breaching Party.",
        "p11": "<strong>10. Full Understanding:</strong> This Agreement reflects the entire understanding between the Parties regarding the matters it covers. It cannot be changed except in writing signed by both Parties before any activity occurs."
    },
    "nda": {
        "title": "Non-Disclosure Agreement",
        "p1": "This Non-Disclosure Agreement (“Agreement”) is made on the date signed below.",
        "p2": "The undersigned individuals or entities (collectively, the “Parties”) willingly and intentionally agree to the following terms:",
        "p3": "<strong>1. Purpose:</strong> The Parties intend to engage in discussions, share information, or collaborate in a capacity that may involve the disclosure of confidential, proprietary, or sensitive information (“Confidential Information”). This Agreement sets forth the obligations of each Party to maintain the secrecy of such information.",
        "p4": "<strong>2. Definition of Confidential Information:</strong> For the purposes of this Agreement, “Confidential Information” shall include, but is not limited to: Any information in written, oral, electronic, or visual form that is not generally known to the public. Business strategies, marketing plans, pricing structures, contracts, agreements, and financial records. Product designs, concepts, prototypes, formulas, code, source files, and technical data. Customer lists, supplier relationships, sales records, prospect data, and trade secrets. Any discussions, proposals, or negotiations between the Parties. Any other information identified as confidential at the time of disclosure or which ought to be reasonably understood as confidential by its nature.",
        "p5": "<strong>3. Exclusions from Confidential Information:</strong> Confidential Information does not include information that: Is or becomes publicly known through no fault of the receiving Party. Was lawfully known by the receiving Party before its disclosure by the other Party. Is lawfully received from a third party without breach of any confidentiality obligation. Is independently developed by the receiving Party without reference to the Confidential Information.",
        "p6": "<strong>4. Confidentiality Obligations:</strong> Each Party agrees to: Hold all Confidential Information in strict confidence and not disclose it to any third party without prior written consent from the disclosing Party. Use the Confidential Information solely for the purpose expressly agreed upon by both Parties. Take all reasonable measures to protect its secrecy and prevent any unauthorized use or disclosure. Limit disclosure of Confidential Information only to employees, contractors, or agents with a need-to-know who are bound by confidentiality obligations no less restrictive than those herein.",
        "p7": "<strong>5. Non-Use and Non-Compete:</strong> Unless otherwise agreed in writing: The receiving Party will not use the Confidential Information for its own benefit or the benefit of any third party beyond the scope agreed upon. The receiving Party will not use the Confidential Information to compete, directly or indirectly, with the business, products, or services of the disclosing Party for a reasonable period from the date of this Agreement.",
        "p8": "<strong>6. Return or Destruction of Materials:</strong> Upon request from the disclosing Party or upon termination of the Parties’ relationship, the receiving Party shall promptly return or destroy all copies, notes, summaries, or other documents containing Confidential Information in any form and provide written confirmation that such return or destruction is complete.",
        "p9": "<strong>7. Term of Confidentiality:</strong> The obligations of this Agreement shall be effective indefinitely from the date of signing, unless otherwise required by law, and shall survive the termination of any business relationship between the Parties.",
        "p10": "<strong>8. Remedies for Breach:</strong> The Parties agree that any unauthorized disclosure or use of Confidential Information may cause irreparable harm for which monetary damages may be inadequate. In such an event, the disclosing Party is entitled to seek injunctive relief, specific performance, and any other remedy available at law or in equity, without the need to post a bond or prove actual damages.",
        "p11": "<strong>9. Legal Compliance:</strong> Nothing in this Agreement shall prohibit the disclosure of Confidential Information if required by law, regulation, court order, or governmental authority, provided that the receiving Party gives the disclosing Party prompt notice to allow them to seek a protective order.",
        "p12": "<strong>10. Entire Agreement:</strong> This Agreement constitutes the entire understanding between the Parties regarding confidentiality and supersedes all prior discussions, understandings, or agreements, whether written or oral, related to the subject matter herein. Any amendments must be in writing and signed by both Parties."
    }
    },
    "es": {
      "content-release": {
        "title": "Acuerdo de Cesión de Contenido",
        "p1": "Este Acuerdo de Cesión de Contenido (“Acuerdo”) se celebra en la fecha firmada a continuación.",
        "p2": "<strong>1. Otorgamiento de Derechos:</strong> El abajo firmante (“Cedente”) otorga irrevocablemente a la otra parte firmante (“Cesionario”) el derecho y permiso para usar, reproducir, publicar, distribuir, transmitir, exhibir y explotar de cualquier otra manera todas las fotografías, videos, grabaciones de audio, textos escritos, imagen, semejanza u otro contenido de medios (colectivamente, el “Contenido”) en el que el Cedente aparece o es identificable, en todos y cada uno de los medios conocidos actualmente o que se desarrollen en el futuro, incluidos, entre otros, medios impresos, televisión, radio, cine, medios digitales, redes sociales, publicidad, materiales promocionales y mercancías.",
        "p3": "<strong>2. Alcance de Uso:</strong> Los derechos otorgados en este documento son mundiales, perpetuos, libres de regalías y pueden ser asignados, transferidos o sublicenciados por el Cesionario a su entera discreción. El Cesionario puede editar, alterar, combinar o modificar el Contenido sin restricciones y sin obligación de notificar o solicitar aprobación adicional del Cedente.",
        "p4": "<strong>3. Compensación:</strong> El Cedente reconoce que esta cesión se otorga voluntariamente y que cualquier compensación (si la hubiera) es una contraprestación total y final por los derechos otorgados en este documento. No se deberán pagos adicionales ni regalías en relación con el uso del Contenido.",
        "p5": "<strong>4. Renuncia de Reclamaciones:</strong> El Cedente renuncia a cualquier derecho de inspeccionar o aprobar el producto final, su uso o cualquier texto o copia que lo acompañe. El Cedente libera y exime para siempre al Cesionario de todas y cada una de las reclamaciones, demandas o causas de acción que el Cedente pueda tener ahora o en el futuro, incluidas, entre otras, reclamaciones por difamación, invasión de la privacidad, violación de los derechos morales o infracción de los derechos de publicidad o personalidad que surjan de o en conexión con el uso del Contenido.",
        "p6": "<strong>5. Capacidad:</strong> El Cedente afirma que tiene al menos 18 años de edad y plena capacidad legal para celebrar este Acuerdo. Si es menor de 18 años, se requiere la firma de un padre o tutor legal.",
        "p7": "<strong>6. Acuerdo Completo:</strong> Este documento constituye el acuerdo completo entre las partes con respecto al Contenido y reemplaza cualquier entendimiento o acuerdo previo, ya sea escrito u oral, sobre el tema aquí tratado. Cualquier modificación o enmienda será nula a menos que se haga por escrito y sea firmada por ambas partes.",
        "p8": "<strong>7. Ley Aplicable:</strong> Este Acuerdo se regirá e interpretará de acuerdo con las leyes de la jurisdicción en la que se ejecuta, sin tener en cuenta sus principios de conflicto de leyes."
      },
      "general-consent": {
        "title": "Acuerdo de Consentimiento Sexual",
        "p1": "Este Acuerdo de Consentimiento Sexual (“Acuerdo”) se celebra en la fecha firmada a continuación. Las personas abajo firmantes (colectivamente, las “Partes”) acuerdan voluntaria e intencionadamente los siguientes términos:",
        "p2": "<strong>1. Participación Voluntaria:</strong> Ambas Partes afirman que su participación en cualquier actividad o contacto sexual es completamente voluntaria, libre del uso de la fuerza, coacción, intimidación, amenazas, chantaje o cualquier influencia indebida. Ninguna de las Partes ha sido intimidada, sobornada o se le ha prometido ninguna recompensa o beneficio a cambio de su participación.",
        "p3": "<strong>2. Capacidad y Estado Mental:</strong> Ambas Partes confirman que, en el momento de la firma y durante todas las actividades acordadas: Tienen la edad legal para consentir según las leyes de la jurisdicción donde se celebra este Acuerdo. Están en pleno uso de sus facultades mentales y tienen plena capacidad para comprender y aceptar estos términos. No están bajo la influencia de alcohol, drogas, medicamentos o cualquier sustancia que afecte su juicio, comprensión o capacidad de toma de decisiones. Han tenido tiempo suficiente para considerar las implicaciones de participar en una actividad sexual y han hecho cualquier pregunta antes de firmar.",
        "p4": "<strong>3. Comprensión del Consentimiento:</strong> Las Partes reconocen que: El consentimiento debe ser informado, otorgado libremente, mutuo y continuo. El consentimiento puede ser retirado por cualquiera de las Partes en cualquier momento, por cualquier motivo y sin explicación. La retirada del consentimiento requiere que la otra Parte cese inmediatamente toda actividad, sin demora ni discusión. La actividad sexual pasada con la otra Parte o con otros no implica ni garantiza el consentimiento para actividades futuras.",
        "p5": "<strong>4. Límites y Respeto:</strong> Las Partes acuerdan comunicar claramente sus niveles de comodidad, límites físicos, límites emocionales y cualquier otra limitación personal antes y durante la actividad. Ambas Partes se comprometen a: Respetar las señales verbales y no verbales que indiquen incomodidad, vacilación o la retirada del consentimiento. Abstenerse de cualquier acto que se sepa o se sospeche razonablemente que cause angustia, daño o perjuicio emocional indebido. Respetar la dignidad personal, la privacidad y la seguridad física de la otra Parte en todo momento.",
        "p6": "<strong>5. Salud y Seguridad:</strong> Las Partes afirman que: Han revelado cualquier condición de salud relevante, incluidas las infecciones de transmisión sexual (ITS) u otras enfermedades, que razonablemente podrían afectar la decisión de la otra Parte de participar. Han discutido y acordado mutuamente las medidas de protección que se utilizarán durante la actividad, incluida la anticoncepción y las normas de higiene. Informarán inmediatamente a la otra Parte si en algún momento se sienten mal, experimentan dolor, angustia o cualquier preocupación médica durante el encuentro.",
        "p7": "<strong>6. Sin Explotación ni Divulgación Pública:</strong> Las Partes acuerdan que: No se realizará ninguna grabación (audio, video o fotográfica) de ninguna actividad sexual sin el consentimiento explícito y mutuo en el momento de la grabación. Si se realizan grabaciones, su uso, almacenamiento y distribución deben acordarse por escrito. No se compartirá públicamente, en línea o con terceros ningún contenido, información o detalle personal sobre la otra Parte sin su consentimiento expreso.",
        "p8": "<strong>7. Duración del Consentimiento:</strong> Este Acuerdo cubre únicamente la actividad sexual que tiene lugar en el período de tiempo inmediato posterior a su ejecución. No otorga un consentimiento abierto o permanente para encuentros futuros. Cualquier actividad posterior requiere un nuevo acuerdo de consentimiento verbal o escrito.",
        "p9": "<strong>8. Liberación Mutua:</strong> Siempre que todas las actividades permanezcan dentro de los límites acordados y que cualquier retirada del consentimiento sea respetada de inmediato, cada Parte libera a la otra de responsabilidad por cualquier reclamación, queja o disputa que surja de la naturaleza consensual del encuentro.",
        "p10": "<strong>9. Limitaciones Legales:</strong> Ambas Partes entienden que: Este Acuerdo no renuncia ni anula ninguna ley aplicable sobre agresión sexual, estupro o incapacidad para dar consentimiento legal. Si posteriormente se descubre que alguna de las Partes carecía de capacidad legal o mental en el momento del encuentro, este Acuerdo es nulo y sin efecto. El incumplimiento de cualquier término de este Acuerdo, incluida la falta de respeto a la retirada del consentimiento, invalida sus protecciones para la Parte infractora.",
        "p11": "<strong>10. Entendimiento Completo:</strong> Este Acuerdo refleja el entendimiento completo entre las Partes sobre los asuntos que cubre. No puede modificarse excepto por escrito y firmado por ambas Partes antes de que ocurra cualquier actividad."
    },
    "nda": {
        "title": "Acuerdo de No Divulgación",
        "p1": "Este Acuerdo de No Divulgación (“Acuerdo”) se celebra en la fecha firmada a continuación.",
        "p2": "Las personas o entidades abajo firmantes (colectivamente, las “Partes”) acuerdan voluntaria e intencionadamente los siguientes términos:",
        "p3": "<strong>1. Propósito:</strong> Las Partes tienen la intención de entablar discusiones, compartir información o colaborar en una capacidad que pueda implicar la divulgación de información confidencial, propietaria o sensible (“Información Confidencial”). Este Acuerdo establece las obligaciones de cada Parte para mantener el secreto de dicha información.",
        "p4": "<strong>2. Definición de Información Confidencial:</strong> Para los fines de este Acuerdo, la “Información Confidencial” incluirá, entre otros: Cualquier información en forma escrita, oral, electrónica o visual que no sea de conocimiento general para el público. Estrategias comerciales, planes de marketing, estructuras de precios, contratos, acuerdos y registros financieros. Diseños de productos, conceptos, prototipos, fórmulas, código, archivos fuente y datos técnicos. Listas de clientes, relaciones con proveedores, registros de ventas, datos de prospectos y secretos comerciales. Cualquier discusión, propuesta o negociación entre las Partes. Cualquier otra información identificada como confidencial en el momento de la divulgación o que razonablemente deba entenderse como confidencial por su naturaleza.",
        "p5": "<strong>3. Exclusiones de la Información Confidencial:</strong> La Información Confidencial no incluye información que: Es o se vuelve de conocimiento público sin culpa de la Parte receptora. Era conocida legalmente por la Parte receptora antes de su divulgación por la otra Parte. Se recibe legalmente de un tercero sin infringir ninguna obligación de confidencialidad. Es desarrollada independientemente por la Parte receptora sin referencia a la Información Confidencial.",
        "p6": "<strong>4. Obligaciones de Confidencialidad:</strong> Cada Parte acuerda: Mantener toda la Información Confidencial en estricta confidencialidad y no divulgarla a ningún tercero sin el consentimiento previo por escrito de la Parte divulgadora. Usar la Información Confidencial únicamente para el propósito expresamente acordado por ambas Partes. Tomar todas las medidas razonables para proteger su secreto y evitar cualquier uso o divulgación no autorizados. Limitar la divulgación de Información Confidencial solo a empleados, contratistas o agentes con necesidad de conocer que estén obligados por obligaciones de confidencialidad no menos restrictivas que las aquí establecidas.",
        "p7": "<strong>5. No Uso y No Competencia:</strong> A menos que se acuerde lo contrario por escrito: La Parte receptora no utilizará la Información Confidencial para su propio beneficio o el de un tercero más allá del alcance acordado. La Parte receptora no utilizará la Información Confidencial para competir, directa o indirectamente, con el negocio, productos o servicios de la Parte divulgadora durante un período razonable a partir de la fecha de este Acuerdo.",
        "p8": "<strong>6. Devolución o Destrucción de Materiales:</strong> A solicitud de la Parte divulgadora o al finalizar la relación de las Partes, la Parte receptora devolverá o destruirá de inmediato todas las copias, notas, resúmenes u otros documentos que contengan Información Confidencial en cualquier forma y proporcionará una confirmación por escrito de que dicha devolución o destrucción se ha completado.",
        "p9": "<strong>7. Plazo de Confidencialidad:</strong> Las obligaciones de este Acuerdo entrarán en vigor indefinidamente a partir de la fecha de la firma, a menos que la ley exija lo contrario, y sobrevivirán a la terminación de cualquier relación comercial entre las Partes.",
        "p10": "<strong>8. Remedios por Incumplimiento:</strong> Las Partes acuerdan que cualquier divulgación o uso no autorizado de Información Confidencial puede causar un daño irreparable para el cual los daños monetarios pueden ser inadecuados. En tal caso, la Parte divulgadora tiene derecho a solicitar medidas cautelares, cumplimiento específico y cualquier otro recurso disponible por ley o en equidad, sin necesidad de depositar una fianza o probar daños reales.",
        "p11": "<strong>9. Cumplimiento Legal:</strong> Nada en este Acuerdo prohibirá la divulgación de Información Confidencial si así lo exige la ley, un reglamento, una orden judicial o una autoridad gubernamental, siempre que la Parte receptora notifique de inmediato a la Parte divulgadora para permitirle solicitar una orden de protección.",
        "p12": "<strong>10. Acuerdo Completo:</strong> Este Acuerdo constituye el entendimiento completo entre las Partes con respecto a la confidencialidad y reemplaza todas las discusiones, entendimientos o acuerdos previos, ya sean escritos u orales, relacionados con el tema aquí tratado. Cualquier enmienda debe hacerse por escrito y ser firmada por ambas Partes."
    }
    },
    "pt": {
      "content-release": {
        "title": "Acordo de Liberação de Conteúdo",
        "p1": "Este Acordo de Liberação de Conteúdo (“Acordo”) é celebrado na data assinada abaixo.",
        "p2": "<strong>1. Concessão de Direitos:</strong> O abaixo assinado (“Liberador”) concede irrevogavelmente à outra parte assinada (“Liberado”) o direito e a permissão para usar, reproduzir, publicar, distribuir, transmitir, exibir e de outra forma explorar todas as fotografias, vídeos, gravações de áudio, textos escritos, imagem, semelhança ou outro conteúdo de mídia (coletivamente, o “Conteúdo”) em que o Liberador aparece ou é identificável, em toda e qualquer mídia agora conhecida ou futuramente desenvolvida, incluindo, mas não se limitando a, impressão, televisão, rádio, cinema, mídia digital, mídias sociais, publicidade, materiais promocionais e mercadorias.",
        "p3": "<strong>2. Escopo de Uso:</strong> Os direitos concedidos aqui são mundiais, perpétuos, isentos de royalties e podem ser atribuídos, transferidos ou sublicenciados pelo Liberado a seu exclusivo critério. O Liberado pode editar, alterar, combinar ou de outra forma modificar o Conteúdo sem restrições e sem qualquer obrigação de notificar ou buscar aprovação adicional do Liberador.",
        "p4": "<strong>3. Compensação:</strong> O Liberador reconhece que esta liberação é dada voluntariamente e que qualquer compensação (se houver) é a contraprestação total и final pelos direitos concedidos aqui. Nenhum pagamento adicional ou royalties será devido em conexão com qualquer uso do Conteúdo.",
        "p5": "<strong>4. Renúncia de Reivindicações:</strong> O Liberador renuncia a qualquer direito de inspecionar ou aprovar o produto final, seu uso ou qualquer texto ou cópia que o acompanhe. O Liberador libera e isenta para sempre o Liberado de toda e qualquer reivindicação, demanda ou causa de ação que o Liberador possa ter agora ou no futuro, incluindo, mas не se limitando a, reivindicações por difamação, invasão de privacidade, violação de direitos morais ou violação de direitos de publicidade ou personalidade decorrentes de ou em conexão com o uso do Conteúdo.",
        "p6": "<strong>5. Capacidade:</strong> O Liberador afirma ter pelo menos 18 anos de idade e plena capacidade legal para celebrar este Acordo. Se for menor de 18 anos, é necessária a assinatura de um pai ou responsável legal.",
        "p7": "<strong>6. Acordo Integral:</strong> Este documento constitui o acordo integral entre as partes com relação ao Conteúdo e substitui quaisquer entendimentos ou acordos anteriores, sejam escritos ou orais, sobre o assunto aqui tratado. Quaisquer modificações ou emendas serão nulas a menos que feitas por escrito e assinadas por ambas as partes.",
        "p8": "<strong>7. Lei Aplicável:</strong> Este Acordo será regido e interpretado de acordo com as leis da jurisdição em que for executado, sem levar em conta seus princípios de conflito de leis."
      },
      "general-consent": {
        "title": "Acordo de Consentimento Sexual",
        "p1": "Este Acordo de Consentimento Sexual (“Acordo”) é celebrado na data assinada abaixo. Os indivíduos abaixo assinados (coletivamente, as “Partes”) concordam voluntária e intencionalmente com os seguintes termos:",
        "p2": "<strong>1. Participação Voluntária:</strong> Ambas as Partes afirmam que sua participação em qualquer atividade ou contato sexual é inteiramente voluntária, livre do uso de força, coerção, coação, ameaças, chantagem ou qualquer influência indevida. Nenhuma das Partes foi intimidada, subornada ou teve a promessa de qualquer recompensa ou benefício em troca da participação.",
        "p3": "<strong>2. Capacidade e Estado de Espírito:</strong> Ambas as Partes confirmam que, no momento da assinatura e durante todas as atividades acordadas: Elas têm a idade legal de consentimento sob as leis da jurisdição onde este Acordo é celebrado. Elas estão sãs e com plena capacidade mental para entender e concordar com estes termos. Elas não estão sob a influência de álcool, drogas, medicamentos ou qualquer substância que prejudique seu julgamento, compreensão ou capacidade de tomada de decisão. Elas tiveram tempo adequado para considerar as implicações de se envolver em atividade sexual e fizeram todas as perguntas antes de assinar.",
        "p4": "<strong>3. Entendimento do Consentimento:</strong> As Partes reconhecem que: O consentimento deve ser informado, dado livremente, mútuo e contínuo. O consentimento pode ser retirado por qualquer uma das Partes a qualquer momento, por qualquer motivo, sem explicação. A retirada do consentimento exige que a outra Parte cesse imediatamente toda a atividade, sem demora ou discussão. A atividade sexual passada com a outra Parte ou com outros não implica ou garante o consentimento para atividades futuras.",
        "p5": "<strong>4. Limites e Respeito:</strong> As Partes concordam em comunicar claramente sobre seus níveis de conforto, limites físicos, limites emocionais e quaisquer outras limitações pessoais antes e durante a atividade. Ambas as Partes se comprometem a: Respeitar os sinais verbais e não verbais que indicam desconforto, hesitação ou a retirada do consentimento. Abster-se de qualquer ato que seja conhecido ou razoavelmente suspeito de causar angústia, dano ou prejuízo emocional indevido. Respeitar a dignidade pessoal, a privacidade e a segurança física da outra Parte em todos os momentos.",
        "p6": "<strong>5. Saúde e Segurança:</strong> As Partes afirmam que: Elas revelaram quaisquer condições de saúde relevantes, incluindo infecções sexualmente transmissíveis (ISTs) ou outras doenças, que poderiam razoavelmente afetar a decisão da outra Parte de participar. Elas discutiram e concordaram mutuamente sobre quaisquer medidas de proteção a serem usadas durante a atividade, incluindo contracepção e padrões de higiene. Elas informarão imediatamente a outra Parte se em algum momento se sentirem mal, sentirem dor, angústia ou tiverem qualquer preocupação médica durante o encontro.",
        "p7": "<strong>6. Sem Exploração ou Divulgação Pública:</strong> As Partes concordam que: Nenhuma gravação (áudio, vídeo ou fotográfica) de qualquer atividade sexual ocorrerá sem o consentimento explícito e mútuo no momento da gravação. Se alguma gravação for feita, seu uso, armazenamento e compartilhamento devem ser acordados por escrito. Nenhum conteúdo, informação ou detalhe pessoal sobre a outra Parte será compartilhado publicamente, online ou com terceiros sem consentimento expresso.",
        "p8": "<strong>7. Duração do Consentimento:</strong> Este Acordo cobre apenas a atividade sexual que ocorre no período de tempo imediato após sua execução. Não concede consentimento aberto ou permanente para encontros futuros. Qualquer atividade subsequente requer um novo acordo de consentimento verbal ou por escrito.",
        "p9": "<strong>8. Liberação Mútua:</strong> Desde que todas as atividades permaneçam dentro dos limites acordados e qualquer retirada de consentimento seja imediatamente respeitada, cada Parte libera a outra de responsabilidade por quaisquer reivindicações, queixas ou disputas decorrentes da natureza consensual do encontro.",
        "p10": "<strong>9. Limitações Legais:</strong> Ambas as Partes entendem que: Este Acordo não renuncia ou anula quaisquer leis aplicáveis sobre agressão sexual, estupro estatutário ou incapacidade de dar consentimento legal. Se for descoberto posteriormente que uma das Partes não tinha capacidade legal ou mental no momento do encontro, este Acordo é nulo e sem efeito. A violação de qualquer termo deste Acordo, incluindo a falha em respeitar a retirada do consentimento, invalida suas proteções para a Parte infratora.",
        "p11": "<strong>10. Entendimento Total:</strong> Este Acordo reflete o entendimento total entre as Partes sobre os assuntos que ele cobre. Não pode ser alterado, exceto por escrito e assinado por ambas as Partes antes que qualquer atividade ocorra."
    },
    "nda": {
        "title": "Acordo de Não Divulgação",
        "p1": "Este Acordo de Não Divulgação (“Acordo”) é celebrado na data assinada abaixo.",
        "p2": "Os indivíduos ou entidades abaixo assinados (coletivamente, as “Partes”) concordam voluntária e intencionalmente com os seguintes termos:",
        "p3": "<strong>1. Propósito:</strong> As Partes pretendem participar de discussões, compartilhar informações ou colaborar em uma capacidade que possa envolver a divulgação de informações confidenciais, proprietárias ou sensíveis (“Informações Confidenciais”). Este Acordo estabelece as obrigações de cada Parte de manter o sigilo de tais informações.",
        "p4": "<strong>2. Definição de Informações Confidenciais:</strong> Para os fins deste Acordo, “Informações Confidenciais” incluirão, mas não se limitam a: Qualquer informação em forma escrita, oral, eletrônica ou visual que não seja geralmente conhecida do público. Estratégias de negócios, planos de marketing, estruturas de preços, contratos, acordos e registros financeiros. Designs de produtos, conceitos, protótipos, fórmulas, código, arquivos-fonte e dados técnicos. Listas de clientes, relacionamentos com fornecedores, registros de vendas, dados de clientes em potencial e segredos comerciais. Quaisquer discussões, propostas ou negociações entre as Partes. Qualquer outra informação identificada como confidencial no momento da divulgação ou que deva ser razoavelmente entendida como confidencial por sua natureza.",
        "p5": "<strong>3. Exclusões de Informações Confidenciais:</strong> Informações Confidenciais não incluem informações que: São ou se tornam publicamente conhecidas sem culpa da Parte receptora. Eram legalmente conhecidas pela Parte receptora antes de sua divulgação pela outra Parte. São recebidas legalmente de um terceiro sem violação de qualquer obrigação de confidencialidade. São desenvolvidas independentemente pela Parte receptora sem referência às Informações Confidenciais.",
        "p6": "<strong>4. Obrigações de Confidencialidade:</strong> Cada Parte concorda em: Manter todas as Informações Confidenciais em estrito sigilo e não divulgá-las a terceiros sem o consentimento prévio por escrito da Parte divulgadora. Usar as Informações Confidenciais exclusivamente para o propósito expressamente acordado por ambas as Partes. Tomar todas as medidas razoáveis para proteger seu sigilo e evitar qualquer uso ou divulgação não autorizados. Limitar a divulgação de Informações Confidenciais apenas a funcionários, contratados ou agentes com necessidade de saber que estejam vinculados por obrigações de confidencialidade não menos restritivas do que as aqui contidas.",
        "p7": "<strong>5. Não Uso e Não Concorrência:</strong> A menos que acordado de outra forma por escrito: A Parte receptora não usará as Informações Confidenciais para seu próprio benefício ou para o benefício de terceiros além do escopo acordado. A Parte receptora não usará as Informações Confidenciais para competir, direta ou indiretamente, com os negócios, produtos ou serviços da Parte divulgadora por um período razoável a partir da data deste Acordo.",
        "p8": "<strong>6. Devolução ou Destruição de Materiais:</strong> Mediante solicitação da Parte divulgadora ou ao término do relacionamento das Partes, a Parte receptora deverá devolver ou destruir prontamente todas as cópias, notas, resumos ou outros documentos que contenham Informações Confidenciais em qualquer formato e fornecer confirmação por escrito de que tal devolução ou destruição está completa.",
        "p9": "<strong>7. Prazo de Confidencialidade:</strong> As obrigações deste Acordo serão efetivas indefinidamente a partir da data de assinatura, a menos que exigido de outra forma por lei, e sobreviverão à rescisão de qualquer relacionamento comercial entre as Partes.",
        "p10": "<strong>8. Remédios por Violação:</strong> As Partes concordam que qualquer divulgação ou uso não autorizado de Informações Confidenciais pode causar danos irreparáveis para os quais os danos monetários podem ser inadequados. Nesse caso, a Parte divulgadora tem o direito de buscar medida cautelar, execução específica e qualquer outro remédio disponível na lei ou em equidade, sem a necessidade de prestar caução ou provar danos reais.",
        "p11": "<strong>9. Conformidade Legal:</strong> Nada neste Acordo proibirá a divulgação de Informações Confidenciais se exigido por lei, regulamento, ordem judicial ou autoridade governamental, desde que a Parte receptora notifique prontamente a Parte divulgadora para permitir que ela busque uma ordem de proteção.",
        "p12": "<strong>10. Acordo Integral:</strong> Este Acordo constitui o entendimento completo entre as Partes com relação à confidencialidade e substitui todas as discussões, entendimentos ou acordos anteriores, sejam escritos ou orais, relacionados ao assunto aqui tratado. Quaisquer emendas devem ser feitas por escrito e assinadas por ambas as Partes."
    }
    },
    "th": {
        "content-release": {
          "title": "ข้อตกลงการอนุญาตให้ใช้เนื้อหา",
          "p1": "ข้อตกลงการอนุญาตให้ใช้เนื้อหานี้ (“ข้อตกลง”) ทำขึ้น ณ วันที่ลงนามด้านล่าง",
          "p2": "<strong>1. การให้สิทธิ์:</strong> ผู้ลงนาม (“ผู้ให้อนุญาต”) ขอมอบสิทธิ์และการอนุญาตที่ไม่สามารถเพิกถอนได้ให้แก่ผู้ลงนามอีกฝ่ายหนึ่ง (“ผู้รับอนุญาต”) ในการใช้, ทำซ้ำ, เผยแพร่, แจกจ่าย, ออกอากาศ, แสดง และใช้ประโยชน์อื่นใดจากภาพถ่าย, วิดีโอ, การบันทึกเสียง, ข้อความเขียน, ภาพลักษณ์, รูปภาพ หรือเนื้อหาสื่ออื่น ๆ ทั้งหมด (รวมเรียกว่า “เนื้อหา”) ที่ผู้ให้อนุญาตปรากฏหรือสามารถระบุตัวตนได้ ซึ่งรวมถึงการใช้งานในสื่อใด ๆ ที่มีอยู่ในปัจจุบันหรือที่จะพัฒนาขึ้นในอนาคต ซึ่งรวมถึงแต่ไม่จำกัดเพียงสื่อสิ่งพิมพ์, โทรทัศน์, วิทยุ, ภาพยนตร์, สื่อดิจิทัล, โซเชียลมีเดีย, การโฆษณา, สื่อส่งเสริมการขาย และสินค้า",
          "p3": "<strong>2. ขอบเขตการใช้งาน:</strong> สิทธิ์ที่มอบให้ในที่นี้มีผลทั่วโลก, เป็นการถาวร, ไม่ต้องเสียค่าลิขสิทธิ์ และผู้รับอนุญาตสามารถมอบหมาย, โอน หรือให้สิทธิ์ช่วงต่อไปได้ตามดุลยพินิจของผู้รับอนุญาต ผู้รับอนุญาตสามารถแก้ไข, เปลี่ยนแปลง, ตัดต่อ, รวม หรือปรับเปลี่ยนเนื้อหาได้โดยไม่มีข้อจำกัดและไม่มีภาระผูกพันที่จะต้องแจ้งหรือขออนุมัติเพิ่มเติมจากผู้ให้อนุญาต",
          "p4": "<strong>3. ค่าตอบแทน:</strong> ผู้ให้อนุญาตรับทราบว่าการให้อนุญาตนี้เป็นไปโดยสมัครใจ และค่าตอบแทนใด ๆ (ถ้ามี) ถือเป็นการตอบแทนที่สมบูรณ์และสิ้นสุดสำหรับสิทธิ์ที่มอบให้ในที่นี้ จะไม่มีการชำระเงินหรือค่าลิขสิทธิ์เพิ่มเติมใด ๆ ที่เกี่ยวข้องกับการใช้เนื้อหา",
          "p5": "<strong>4. การสละสิทธิ์ในการเรียกร้อง:</strong> ผู้ให้อนุญาตสละสิทธิ์ในการตรวจสอบหรืออนุมัติผลิตภัณฑ์ขั้นสุดท้าย, การใช้งาน หรือข้อความหรือเนื้อหาประกอบใด ๆ ผู้ให้อนุญาตปลดเปลื้องและปลดหนี้ผู้รับอนุญาตจากการเรียกร้อง, ความต้องการ หรือมูลเหตุแห่งคดีใด ๆ ทั้งหมดที่ผู้ให้อนุญาตอาจมีในปัจจุบันหรือในอนาคต ซึ่งรวมถึงแต่ไม่จำกัดเพียงการเรียกร้องค่าเสียหายจากการหมิ่นประมาท, การบุกรุกความเป็นส่วนตัว, การละเมิดสิทธิ์ทางศีลธรรม หรือการละเมิดสิทธิ์ในชื่อเสียงหรือบุคลิกภาพที่เกิดขึ้นจากหรือเกี่ยวข้องกับการใช้เนื้อหา",
          "p6": "<strong>5. ความสามารถทางกฎหมาย:</strong> ผู้ให้อนุญาตยืนยันว่ามีอายุอย่างน้อย 18 ปีบริบูรณ์และมีความสามารถทางกฎหมายอย่างเต็มที่ในการทำข้อตกลงนี้ หากอายุต่ำกว่า 18 ปี จะต้องมีลายเซ็นของผู้ปกครองหรือผู้ดูแลตามกฎหมาย",
          "p7": "<strong>6. ข้อตกลงทั้งหมด:</strong> เอกสารนี้ถือเป็นข้อตกลงทั้งหมดระหว่างคู่สัญญาทั้งสองฝ่ายเกี่ยวกับเนื้อหาและใช้แทนความเข้าใจหรือข้อตกลงใด ๆ ก่อนหน้านี้ ไม่ว่าจะเป็นลายลักษณ์อักษรหรือวาจา เกี่ยวกับเรื่องที่ระบุไว้ในที่นี้ การแก้ไขหรือเปลี่ยนแปลงใด ๆ จะไม่มีผลบังคับใช้เว้นแต่จะทำเป็นลายลักษณ์อักษรและลงนามโดยคู่สัญญาทั้งสองฝ่าย",
          "p8": "<strong>7. กฎหมายที่ใช้บังคับ:</strong> ข้อตกลงนี้จะถูกควบคุมและตีความตามกฎหมายของเขตอำนาจศาลที่ทำขึ้น โดยไม่คำนึงถึงหลักการขัดกันแห่งกฎหมาย"
        },
        "general-consent": {
            "title": "ข้อตกลงความยินยอมทางเพศ",
            "p1": "ข้อตกลงความยินยอมทางเพศนี้ (“ข้อตกลง”) ทำขึ้น ณ วันที่ลงนามด้านล่าง บุคคลผู้ลงนาม (เรียกรวมกันว่า “คู่สัญญา”) ตกลงโดยสมัครใจและโดยเจตนาตามข้อกำหนดต่อไปนี้:",
            "p2": "<strong>1. การเข้าร่วมโดยสมัครใจ:</strong> คู่สัญญาทั้งสองฝ่ายยืนยันว่าการเข้าร่วมในกิจกรรมหรือการสัมผัสทางเพศใด ๆ เป็นไปโดยสมัครใจอย่างสมบูรณ์ ปราศจากการใช้กำลัง การบังคับ การชักจูง การข่มขู่ การแบล็กเมล์ หรืออิทธิพลที่ไม่เหมาะสมใด ๆ ไม่มีฝ่ายใดถูกข่มขู่ ติดสินบน หรือสัญญาว่าจะให้รางวัลหรือผลประโยชน์ใด ๆ เพื่อแลกกับการเข้าร่วม",
            "p3": "<strong>2. ความสามารถและสภาวะทางจิตใจ:</strong> คู่สัญญาทั้งสองฝ่ายยืนยันว่า ในขณะที่ลงนามและระหว่างกิจกรรมที่ตกลงกันทั้งหมด: พวกเขามีอายุตามกฎหมายที่สามารถให้ความยินยอมได้ภายใต้กฎหมายของเขตอำนาจศาลที่ทำข้อตกลงนี้ พวกเขามีสติสัมปชัญญะและความสามารถทางจิตใจอย่างสมบูรณ์ในการทำความเข้าใจและยอมรับข้อกำหนดเหล่านี้ พวกเขาไม่ได้อยู่ภายใต้อิทธิพลของแอลกอฮอล์ ยาเสพติด ยา หรือสารที่ทำให้ความสามารถในการตัดสินใจ ความเข้าใจ หรือการตัดสินใจลดลง พวกเขาได้มีเวลาเพียงพอในการพิจารณาผลกระทบของการมีกิจกรรมทางเพศและได้ถามคำถามใด ๆ ก่อนลงนาม",
            "p4": "<strong>3. ความเข้าใจเกี่ยวกับความยินยอม:</strong> คู่สัญญารับทราบว่า: ความยินยอมต้องได้รับข้อมูลอย่างครบถ้วน ให้โดยอิสระ เป็นความยินยอมร่วมกัน และต่อเนื่อง ความยินยอมสามารถถอนได้โดยฝ่ายใดฝ่ายหนึ่ง ณ เวลาใดก็ได้ ไม่ว่าด้วยเหตุผลใดก็ตาม โดยไม่ต้องอธิบาย การถอนความยินยอมทำให้ฝ่ายอื่นต้องหยุดกิจกรรมทั้งหมดทันที โดยไม่ล่าช้าหรือโต้เถียง การเข้าร่วมกิจกรรมทางเพศในอดีตกับอีกฝ่ายหรือกับผู้อื่นไม่ได้หมายความถึงหรือรับประกันความยินยอมสำหรับกิจกรรมในอนาคต",
            "p5": "<strong>4. ขอบเขตและความเคารพ:</strong> คู่สัญญาตกลงที่จะสื่อสารอย่างชัดเจนเกี่ยวกับระดับความสะดวกสบาย ขอบเขตทางกายภาพ ขอบเขตทางอารมณ์ และข้อจำกัดส่วนบุคคลอื่น ๆ ก่อนและระหว่างกิจกรรม คู่สัญญาทั้งสองฝ่ายมุ่งมั่นที่จะ: เคารพสัญญาณทางวาจาและไม่ใช่วาจาที่บ่งชี้ถึงความไม่สะดวก ความลังเล หรือการถอนความยินยอม หลีกเลี่ยงการกระทำที่ทราบหรือสงสัยอย่างมีเหตุผลว่าจะก่อให้เกิดความทุกข์ การบาดเจ็บ หรือความเสียหายทางอารมณ์อย่างไม่เหมาะสม เคารพในศักดิ์ศรีส่วนบุคคล ความเป็นส่วนตัว และความปลอดภัยทางกายภาพของอีกฝ่ายตลอดเวลา",
            "p6": "<strong>5. สุขภาพและความปลอดภัย:</strong> คู่สัญญายืนยันว่า: พวกเขาได้เปิดเผยภาวะสุขภาพที่เกี่ยวข้องใด ๆ รวมถึงโรคติดต่อทางเพศสัมพันธ์ (STIs) หรือโรคอื่น ๆ ที่อาจส่งผลกระทบอย่างมีเหตุผลต่อการตัดสินใจของอีกฝ่ายในการเข้าร่วม พวกเขาได้หารือและตกลงร่วมกันเกี่ยวกับมาตรการป้องกันใด ๆ ที่จะใช้ระหว่างกิจกรรม รวมถึงการป้องกันและมาตรฐานสุขอนามัย พวกเขาจะแจ้งให้อีกฝ่ายทราบทันทีหากเมื่อใดก็ตามที่พวกเขารู้สึกไม่สบาย ปวด ทุกข์ หรือมีความกังวลทางการแพทย์ใด ๆ ระหว่างการพบกัน",
            "p7": "<strong>6. ไม่มีการแสวงหาประโยชน์หรือการเปิดเผยต่อสาธารณะ:</strong> คู่สัญญาตกลงว่า: จะไม่มีการบันทึก (เสียง วิดีโอ หรือภาพถ่าย) กิจกรรมทางเพศใด ๆ โดยไม่ได้รับความยินยอมร่วมกันอย่างชัดเจน ณ เวลาที่ทำการบันทึก หากมีการบันทึกใด ๆ การใช้ การจัดเก็บ และการแบ่งปันการบันทึกนั้นจะต้องตกลงกันเป็นลายลักษณ์อักษร จะไม่มีการแบ่งปันเนื้อหา ข้อมูล หรือรายละเอียดส่วนบุคคลเกี่ยวกับอีกฝ่ายต่อสาธารณะ ออนไลน์ หรือกับบุคคลที่สามโดยไม่ได้รับความยินยอมอย่างชัดแจ้ง",
            "p8": "<strong>7. ระยะเวลาของความยินยอม:</strong> ข้อตกลงนี้ครอบคลุมเฉพาะกิจกรรมทางเพศที่เกิดขึ้นในช่วงเวลาทันทีหลังจากการลงนาม ไม่ได้ให้ความยินยอมแบบปลายเปิดหรือถาวรสำหรับการพบกันในอนาคต กิจกรรมใด ๆ ในภายหลังจะต้องได้รับความยินยอมด้วยวาจาหรือลายลักษณ์อักษรอีกครั้ง",
            "p9": "<strong>8. การปลดเปลื้องซึ่งกันและกัน:</strong> หากกิจกรรมทั้งหมดอยู่ภายในขอบเขตที่ตกลงกันและการถอนความยินยอมทั้งหมดได้รับการเคารพทันที แต่ละฝ่ายจะปลดเปลื้องอีกฝ่ายจากความรับผิดชอบในการเรียกร้อง การร้องเรียน หรือข้อพิพาทที่เกิดขึ้นจากลักษณะที่เป็นความยินยอมของการพบกัน",
            "p10": "<strong>9. ข้อจำกัดทางกฎหมาย:</strong> คู่สัญญาทั้งสองฝ่ายเข้าใจว่า: ข้อตกลงนี้ไม่สละสิทธิ์หรือลบล้างกฎหมายที่บังคับใช้ใด ๆ เกี่ยวกับการล่วงละเมิดทางเพศ การข่มขืนผู้เยาว์ หรือการไร้ความสามารถในการให้ความยินยอม หากภายหลังพบว่าฝ่ายใดฝ่ายหนึ่งไม่สามารถให้ความยินยอมทางกฎหมายหรือทางจิตใจได้ ณ เวลาที่พบกัน ข้อตกลงนี้ถือเป็นโมฆะ การละเมิดข้อกำหนดใด ๆ ของข้อตกลงนี้ รวมถึงการไม่เคารพการถอนความยินยอม จะทำให้การคุ้มครองสำหรับฝ่ายที่ละเมิดเป็นโมฆะ",
            "p11": "<strong>10. ความเข้าใจทั้งหมด:</strong> ข้อตกลงนี้สะท้อนถึงความเข้าใจทั้งหมดระหว่างคู่สัญญาเกี่ยวกับเรื่องที่ครอบคลุม ไม่สามารถเปลี่ยนแปลงได้ยกเว้นเป็นลายลักษณ์อักษรและลงนามโดยคู่สัญญาทั้งสองฝ่ายก่อนที่จะมีกิจกรรมเกิดขึ้น"
        },
        "nda": {
            "title": "ข้อตกลงไม่เปิดเผยข้อมูล",
            "p1": "ข้อตกลงไม่เปิดเผยข้อมูลนี้ (“ข้อตกลง”) ทำขึ้น ณ วันที่ลงนามด้านล่าง",
            "p2": "บุคคลหรือนิติบุคคลผู้ลงนาม (เรียกรวมกันว่า “คู่สัญญา”) ตกลงโดยสมัครใจและโดยเจตนาตามข้อกำหนดต่อไปนี้:",
            "p3": "<strong>1. วัตถุประสงค์:</strong> คู่สัญญามีเจตนาที่จะเข้าร่วมในการหารือ แบ่งปันข้อมูล หรือทำงานร่วมกันในลักษณะที่อาจเกี่ยวข้องกับการเปิดเผยข้อมูลที่เป็นความลับ เป็นกรรมสิทธิ์ หรือมีความละเอียดอ่อน (“ข้อมูลที่เป็นความลับ”) ข้อตกลงนี้กำหนดภาระผูกพันของแต่ละฝ่ายในการรักษาความลับของข้อมูลดังกล่าว",
            "p4": "<strong>2. คำจำกัดความของข้อมูลที่เป็นความลับ:</strong> เพื่อวัตถุประสงค์ของข้อตกลงนี้ “ข้อมูลที่เป็นความลับ” รวมถึงแต่ไม่จำกัดเพียง: ข้อมูลใด ๆ ที่เป็นลายลักษณ์อักษร วาจา อิเล็กทรอนิกส์ หรือภาพที่ไม่เป็นที่รู้จักโดยทั่วไปต่อสาธารณะ กลยุทธ์ทางธุรกิจ แผนการตลาด โครงสร้างราคา สัญญา ข้อตกลง และบันทึกทางการเงิน การออกแบบผลิตภัณฑ์ แนวคิด ต้นแบบ สูตร โค้ด ซอร์สไฟล์ และข้อมูลทางเทคนิค รายชื่อลูกค้า ความสัมพันธ์กับซัพพลายเออร์ บันทึกการขาย ข้อมูลลูกค้าเป้าหมาย และความลับทางการค้า การหารือ ข้อเสนอ หรือการเจรจาใด ๆ ระหว่างคู่สัญญา ข้อมูลอื่นใดที่ระบุว่าเป็นความลับ ณ เวลาที่เปิดเผยหรือที่ควรเข้าใจอย่างมีเหตุผลว่าเป็นความลับตามลักษณะของข้อมูล",
            "p5": "<strong>3. ข้อยกเว้นจากข้อมูลที่เป็นความลับ:</strong> ข้อมูลที่เป็นความลับไม่รวมถึงข้อมูลที่: เป็นหรือกลายเป็นที่รู้จักต่อสาธารณะโดยไม่ใช่ความผิดของฝ่ายที่รับข้อมูล เป็นที่รู้จักโดยชอบด้วยกฎหมายของฝ่ายที่รับข้อมูลก่อนการเปิดเผยโดยอีกฝ่ายหนึ่ง ได้รับโดยชอบด้วยกฎหมายจากบุคคลที่สามโดยไม่ละเมิดภาระผูกพันในการรักษาความลับใด ๆ ได้รับการพัฒนาโดยอิสระโดยฝ่ายที่รับข้อมูลโดยไม่ได้อ้างอิงถึงข้อมูลที่เป็นความลับ",
            "p6": "<strong>4. ภาระผูกพันในการรักษาความลับ:</strong> แต่ละฝ่ายตกลงที่จะ: รักษาข้อมูลที่เป็นความลับทั้งหมดเป็นความลับอย่างเคร่งครัดและไม่เปิดเผยต่อบุคคลที่สามใด ๆ โดยไม่ได้รับความยินยอมเป็นลายลักษณ์อักษรล่วงหน้าจากฝ่ายที่เปิดเผยข้อมูล ใช้ข้อมูลที่เป็นความลับเพื่อวัตถุประสงค์ที่ตกลงกันไว้อย่างชัดแจ้งโดยคู่สัญญาทั้งสองฝ่ายเท่านั้น ใช้มาตรการที่สมเหตุสมผลทั้งหมดเพื่อปกป้องความลับและป้องกันการใช้หรือการเปิดเผยข้อมูลที่เป็นความลับโดยไม่ได้รับอนุญาต จำกัดการเปิดเผยข้อมูลที่เป็นความลับเฉพาะพนักงาน ผู้รับจ้าง หรือตัวแทนที่มีความจำเป็นต้องรู้และผูกพันตามภาระผูกพันในการรักษาความลับที่ไม่น้อยไปกว่าที่ระบุไว้ในข้อตกลงนี้",
            "p7": "<strong>5. การไม่ใช้และการไม่แข่งขัน:</strong> เว้นแต่จะตกลงเป็นอย่างอื่นเป็นลายลักษณ์อักษร: ฝ่ายที่รับข้อมูลจะไม่ใช้ข้อมูลที่เป็นความลับเพื่อประโยชน์ของตนเองหรือประโยชน์ของบุคคลที่สามใด ๆ นอกเหนือจากขอบเขตที่ตกลงกันไว้ ฝ่ายที่รับข้อมูลจะไม่ใช้ข้อมูลที่เป็นความลับเพื่อแข่งขันโดยตรงหรือโดยอ้อมกับธุรกิจ ผลิตภัณฑ์ หรือบริการของฝ่ายที่เปิดเผยข้อมูลเป็นระยะเวลาที่สมเหตุสมผลนับจากวันที่ของข้อตกลงนี้",
            "p8": "<strong>6. การคืนหรือทำลายเอกสาร:</strong> เมื่อได้รับการร้องขอจากฝ่ายที่เปิดเผยข้อมูลหรือเมื่อความสัมพันธ์ของคู่สัญญาสิ้นสุดลง ฝ่ายที่รับข้อมูลจะต้องคืนหรือทำลายสำเนา บันทึกย่อ สรุป หรือเอกสารอื่น ๆ ทั้งหมดที่มีข้อมูลที่เป็นความลับในทุกรูปแบบโดยทันที และยืนยันเป็นลายลักษณ์อักษรว่าการคืนหรือทำลายดังกล่าวได้เสร็จสิ้นแล้ว",
            "p9": "<strong>7. ระยะเวลาของการรักษาความลับ:</strong> ภาระผูกพันของข้อตกลงนี้จะมีผลบังคับใช้อย่างไม่มีกำหนดนับจากวันที่ลงนาม เว้นแต่กฎหมายจะกำหนดเป็นอย่างอื่น และจะยังคงมีผลบังคับใช้ต่อไปแม้ว่าความสัมพันธ์ทางธุรกิจระหว่างคู่สัญญาจะสิ้นสุดลง",
            "p10": "<strong>8. การเยียวยาสำหรับการละเมิด:</strong> คู่สัญญาตกลงว่าการเปิดเผยหรือการใช้ข้อมูลที่เป็นความลับโดยไม่ได้รับอนุญาตอาจก่อให้เกิดความเสียหายที่ไม่สามารถแก้ไขได้ ซึ่งค่าเสียหายที่เป็นตัวเงินอาจไม่เพียงพอ ในกรณีดังกล่าว ฝ่ายที่เปิดเผยข้อมูลมีสิทธิ์ที่จะขอคำสั่งห้าม การบังคับให้ปฏิบัติตามสัญญา และการเยียวยาอื่นใดที่มีอยู่ตามกฎหมายหรือหลักความยุติธรรม โดยไม่จำเป็นต้องวางประกันหรือพิสูจน์ความเสียหายที่เกิดขึ้นจริง",
            "p11": "<strong>9. การปฏิบัติตามกฎหมาย:</strong> ไม่มีข้อความใดในข้อตกลงนี้ที่จะห้ามการเปิดเผยข้อมูลที่เป็นความลับหากกฎหมาย ข้อบังคับ คำสั่งศาล หรือหน่วยงานของรัฐกำหนด โดยมีเงื่อนไขว่าฝ่ายที่รับข้อมูลจะต้องแจ้งให้ฝ่ายที่เปิดเผยข้อมูลทราบโดยทันทีเพื่อให้พวกเขาสามารถใช้มาตรการป้องกันได้",
            "p12": "<strong>10. ข้อตกลงทั้งหมด:</strong> ข้อตกลงนี้ถือเป็นความเข้าใจทั้งหมดระหว่างคู่สัญญาเกี่ยวกับการรักษาความลับและใช้แทนการหารือ ความเข้าใจ หรือข้อตกลงใด ๆ ก่อนหน้านี้ ไม่ว่าจะเป็นลายลักษณ์อักษรหรือวาจา ที่เกี่ยวข้องกับเรื่องที่ระบุไว้ในที่นี้ การแก้ไขใด ๆ จะต้องทำเป็นลายลักษณ์อักษรและลงนามโดยคู่สัญญาทั้งสองฝ่าย"
        }
    }
  }